import { TechnologyTemplate } from './types';

export const technologies: TechnologyTemplate[] = [
  {
    id: 'node',
    name: 'Node.js',
    icon: '🟢',
    category: 'language',
    description: 'JavaScript runtime environment',
    files: {
      gitignore: [
        '# Dependencies',
        'node_modules/',
        'package-lock.json',
        'yarn.lock',
        'pnpm-lock.yaml',
        '',
        '# Build outputs',
        'dist/',
        'build/',
        '.next/',
        '.nuxt/',
        '',
        '# Logs',
        'logs/',
        '*.log',
        'npm-debug.log*',
        'yarn-debug.log*',
        'yarn-error.log*',
        '',
        '# Runtime data',
        'pids/',
        '*.pid',
        '*.seed',
        '*.pid.lock',
        '',
        '# Coverage',
        'coverage/',
        '.nyc_output/',
      ],
      gitattributes: [
        '*.js text eol=lf',
        '*.ts text eol=lf',
        '*.json text eol=lf',
        'package-lock.json -diff',
        'yarn.lock -diff',
      ],
      editorconfig: [
        '[*.{js,jsx,ts,tsx}]',
        'indent_style = space',
        'indent_size = 2',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
      ],
      dockerignore: [
        'node_modules/',
        'npm-debug.log',
        'yarn-debug.log',
        'yarn-error.log',
        '.git/',
        '.gitignore',
        'README.md',
        'docker-compose*.yml',
        '.dockerignore',
        'Dockerfile*',
      ],
    },
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    icon: '▲',
    category: 'framework',
    description: 'React framework for production',
    files: {
      gitignore: [
        '# Next.js',
        '.next/',
        'out/',
        '.vercel/',
        '',
        '# Build',
        'build/',
        '',
        '# Dependencies',
        'node_modules/',
        '',
        '# TypeScript',
        '*.tsbuildinfo',
        'next-env.d.ts',
        '',
        '# Testing',
        'coverage/',
        '.nyc_output/',
        '',
        '# Debug',
        'npm-debug.log*',
        'yarn-debug.log*',
        'yarn-error.log*',
        '',
        '# Local env files',
        '.env*.local',
        '.env.development.local',
        '.env.test.local',
        '.env.production.local',
      ],
      gitattributes: [
        '*.js text eol=lf',
        '*.jsx text eol=lf',
        '*.ts text eol=lf',
        '*.tsx text eol=lf',
        '*.css text eol=lf',
        '*.md text eol=lf',
        'package-lock.json -diff',
      ],
      editorconfig: [
        '[*.{js,jsx,ts,tsx,css,scss}]',
        'indent_style = space',
        'indent_size = 2',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
      ],
      dockerignore: [
        '.next/',
        'node_modules/',
        '.git/',
        '.gitignore',
        'README.md',
        '.env*.local',
        'Dockerfile*',
        'docker-compose*.yml',
      ],
    },
  },
  {
    id: 'react',
    name: 'React',
    icon: '⚛️',
    category: 'framework',
    description: 'JavaScript library for building UIs',
    files: {
      gitignore: [
        '# Dependencies',
        'node_modules/',
        '',
        '# Build',
        'build/',
        'dist/',
        '',
        '# Testing',
        'coverage/',
        '',
        '# Misc',
        '.DS_Store',
        '*.log',
        '',
        '# Environment',
        '.env.local',
        '.env.development.local',
        '.env.test.local',
        '.env.production.local',
      ],
      editorconfig: [
        '[*.{js,jsx,ts,tsx}]',
        'indent_style = space',
        'indent_size = 2',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
      ],
    },
  },
  {
    id: 'python',
    name: 'Python',
    icon: '🐍',
    category: 'language',
    description: 'High-level programming language',
    files: {
      gitignore: [
        '# Byte-compiled / optimized / DLL files',
        '__pycache__/',
        '*.py[cod]',
        '*$py.class',
        '',
        '# Virtual environments',
        'venv/',
        'env/',
        '.venv/',
        '.env/',
        'ENV/',
        '',
        '# Distribution / packaging',
        'build/',
        'dist/',
        'eggs/',
        '*.egg-info/',
        '*.egg',
        '',
        '# Testing',
        '.pytest_cache/',
        '.coverage',
        'htmlcov/',
        '.tox/',
        '.nox/',
        '',
        '# Jupyter Notebook',
        '.ipynb_checkpoints/',
        '',
        '# Type checkers',
        '.mypy_cache/',
        '.pytype/',
      ],
      gitattributes: [
        '*.py text eol=lf',
        '*.pyw text eol=lf',
        '*.pyx text eol=lf',
        '*.pxd text eol=lf',
        '*.pxi text eol=lf',
      ],
      editorconfig: [
        '[*.py]',
        'indent_style = space',
        'indent_size = 4',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
        'max_line_length = 88',
      ],
      dockerignore: [
        '__pycache__/',
        '*.pyc',
        '*.pyo',
        '*.pyd',
        '.Python',
        'venv/',
        '.venv/',
        '.git/',
        '.gitignore',
        'README.md',
        'Dockerfile*',
      ],
    },
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    icon: '🔷',
    category: 'language',
    description: 'Typed superset of JavaScript',
    files: {
      gitignore: [
        '# TypeScript',
        '*.tsbuildinfo',
        '',
        '# Build output',
        'dist/',
        'build/',
        'out/',
        '',
        '# Dependencies',
        'node_modules/',
        '',
        '# Source maps',
        '*.map',
      ],
      gitattributes: [
        '*.ts text eol=lf',
        '*.tsx text eol=lf',
        '*.d.ts text eol=lf',
      ],
      editorconfig: [
        '[*.{ts,tsx}]',
        'indent_style = space',
        'indent_size = 2',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
      ],
    },
  },
  {
    id: 'rust',
    name: 'Rust',
    icon: '🦀',
    category: 'language',
    description: 'Systems programming language',
    files: {
      gitignore: [
        '# Generated by Cargo',
        '/target/',
        '',
        '# Remove Cargo.lock for libraries',
        '# Cargo.lock',
        '',
        '# Backup files',
        '**/*.rs.bk',
        '',
        '# MSVC Windows builds',
        '*.pdb',
      ],
      gitattributes: [
        '*.rs text eol=lf',
        'Cargo.toml text eol=lf',
        'Cargo.lock text eol=lf -diff',
      ],
      editorconfig: [
        '[*.rs]',
        'indent_style = space',
        'indent_size = 4',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
      ],
    },
  },
  {
    id: 'go',
    name: 'Go',
    icon: '🐹',
    category: 'language',
    description: 'Open source programming language',
    files: {
      gitignore: [
        '# Binaries',
        '*.exe',
        '*.exe~',
        '*.dll',
        '*.so',
        '*.dylib',
        '',
        '# Test binary',
        '*.test',
        '',
        '# Output of go coverage tool',
        '*.out',
        '',
        '# Go workspace file',
        'go.work',
        '',
        '# Vendor directory',
        'vendor/',
      ],
      gitattributes: [
        '*.go text eol=lf',
        'go.mod text eol=lf',
        'go.sum text eol=lf -diff',
      ],
      editorconfig: [
        '[*.go]',
        'indent_style = tab',
        'indent_size = 4',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
      ],
    },
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: '🐳',
    category: 'tool',
    description: 'Container platform',
    files: {
      gitignore: [
        '# Docker',
        '.docker/',
        'docker-compose*.override.yml',
      ],
      dockerignore: [
        '.git/',
        '.gitignore',
        'README.md',
        'LICENSE',
        '.env*',
        'docker-compose*.yml',
        'Dockerfile*',
        '.dockerignore',
        'docs/',
        'tests/',
        '__tests__/',
        '*.md',
        '.editorconfig',
        '.prettierrc',
        '.eslintrc*',
      ],
    },
  },
  {
    id: 'vscode',
    name: 'VS Code',
    icon: '💙',
    category: 'ide',
    description: 'Visual Studio Code editor',
    files: {
      gitignore: [
        '# VS Code',
        '.vscode/*',
        '!.vscode/settings.json',
        '!.vscode/tasks.json',
        '!.vscode/launch.json',
        '!.vscode/extensions.json',
        '!.vscode/*.code-snippets',
        '',
        '# Local History',
        '.history/',
        '',
        '# Built VS Code Extensions',
        '*.vsix',
      ],
    },
  },
  {
    id: 'jetbrains',
    name: 'JetBrains',
    icon: '🧠',
    category: 'ide',
    description: 'IntelliJ-based IDEs',
    files: {
      gitignore: [
        '# JetBrains IDEs',
        '.idea/',
        '*.iml',
        '*.ipr',
        '*.iws',
        '',
        '# CMake',
        'cmake-build-*/',
        '',
        '# File-based project format',
        '*.iws',
        '',
        '# IntelliJ',
        'out/',
        '',
        '# JIRA plugin',
        'atlassian-ide-plugin.xml',
      ],
    },
  },
  {
    id: 'macos',
    name: 'macOS',
    icon: '🍎',
    category: 'os',
    description: 'Apple macOS files',
    files: {
      gitignore: [
        '# macOS',
        '.DS_Store',
        '.AppleDouble',
        '.LSOverride',
        '',
        '# Icon must end with two \\r',
        'Icon',
        '',
        '# Thumbnails',
        '._*',
        '',
        '# Spotlight',
        '.Spotlight-V100',
        '.Trashes',
      ],
    },
  },
  {
    id: 'windows',
    name: 'Windows',
    icon: '🪟',
    category: 'os',
    description: 'Microsoft Windows files',
    files: {
      gitignore: [
        '# Windows',
        'Thumbs.db',
        'Thumbs.db:encryptable',
        'ehthumbs.db',
        'ehthumbs_vista.db',
        '',
        '# Folder config file',
        '[Dd]esktop.ini',
        '',
        '# Recycle Bin',
        '$RECYCLE.BIN/',
        '',
        '# Shortcuts',
        '*.lnk',
      ],
    },
  },
  {
    id: 'linux',
    name: 'Linux',
    icon: '🐧',
    category: 'os',
    description: 'Linux system files',
    files: {
      gitignore: [
        '# Linux',
        '*~',
        '',
        '# Temporary files',
        '.fuse_hidden*',
        '.directory',
        '.Trash-*',
        '.nfs*',
      ],
    },
  },
  {
    id: 'vue',
    name: 'Vue.js',
    icon: '💚',
    category: 'framework',
    description: 'Progressive JavaScript framework',
    files: {
      gitignore: [
        '# Vue.js',
        '.nuxt/',
        'dist/',
        '',
        '# Dependencies',
        'node_modules/',
        '',
        '# Local env files',
        '.env.local',
        '.env.*.local',
        '',
        '# Logs',
        'npm-debug.log*',
        'yarn-debug.log*',
        'yarn-error.log*',
        'pnpm-debug.log*',
      ],
      editorconfig: [
        '[*.{vue,js,ts}]',
        'indent_style = space',
        'indent_size = 2',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
      ],
    },
  },
  {
    id: 'angular',
    name: 'Angular',
    icon: '🅰️',
    category: 'framework',
    description: 'Web application framework',
    files: {
      gitignore: [
        '# Angular',
        '.angular/',
        'dist/',
        '',
        '# Dependencies',
        'node_modules/',
        '',
        '# IDE',
        '.idea/',
        '.vscode/',
        '',
        '# Misc',
        '*.log',
        '.env',
      ],
    },
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    icon: '🎨',
    category: 'tool',
    description: 'Utility-first CSS framework',
    files: {
      gitignore: [
        '# Tailwind',
        '.tailwindcss/',
      ],
      editorconfig: [
        '[*.{css,scss}]',
        'indent_style = space',
        'indent_size = 2',
        'end_of_line = lf',
        'charset = utf-8',
        'trim_trailing_whitespace = true',
        'insert_final_newline = true',
      ],
    },
  },
  {
    id: 'django',
    name: 'Django',
    icon: '🌿',
    category: 'framework',
    description: 'Python web framework',
    files: {
      gitignore: [
        '# Django',
        '*.log',
        'local_settings.py',
        'db.sqlite3',
        'db.sqlite3-journal',
        '',
        '# Static files',
        '/static/',
        '/staticfiles/',
        '',
        '# Media files',
        '/media/',
        '',
        '# Python',
        '__pycache__/',
        '*.py[cod]',
        'venv/',
        '.env',
      ],
      dockerignore: [
        '__pycache__/',
        '*.pyc',
        'venv/',
        '.venv/',
        '.git/',
        '*.sqlite3',
        'media/',
        'staticfiles/',
      ],
    },
  },
  {
    id: 'flask',
    name: 'Flask',
    icon: '🧪',
    category: 'framework',
    description: 'Python micro web framework',
    files: {
      gitignore: [
        '# Flask',
        'instance/',
        '.webassets-cache',
        '',
        '# Python',
        '__pycache__/',
        '*.py[cod]',
        'venv/',
        '.env',
        '',
        '# Database',
        '*.db',
        '*.sqlite',
      ],
    },
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    icon: '🐘',
    category: 'database',
    description: 'Relational database',
    files: {
      gitignore: [
        '# PostgreSQL',
        '*.sql.gz',
        '*.dump',
        'pg_data/',
      ],
      dockerignore: [
        '*.sql.gz',
        '*.dump',
        'pg_data/',
      ],
    },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    icon: '🍃',
    category: 'database',
    description: 'NoSQL document database',
    files: {
      gitignore: [
        '# MongoDB',
        'data/db/',
        '*.bson',
        'mongod.lock',
      ],
    },
  },
  {
    id: 'aws',
    name: 'AWS',
    icon: '☁️',
    category: 'cloud',
    description: 'Amazon Web Services',
    files: {
      gitignore: [
        '# AWS',
        '.aws/',
        'aws-exports.js',
        'aws-exports.ts',
        '',
        '# SAM',
        '.aws-sam/',
        'samconfig.toml',
        '',
        '# Amplify',
        'amplify/.config/local-*',
        'amplify/backend/amplify-meta.json',
        'amplify/team-provider-info.json',
      ],
    },
  },
  {
    id: 'terraform',
    name: 'Terraform',
    icon: '🏗️',
    category: 'tool',
    description: 'Infrastructure as code',
    files: {
      gitignore: [
        '# Terraform',
        '.terraform/',
        '.terraform.lock.hcl',
        '*.tfstate',
        '*.tfstate.*',
        'crash.log',
        'crash.*.log',
        '*.tfvars',
        '*.tfvars.json',
        'override.tf',
        'override.tf.json',
        '*_override.tf',
        '*_override.tf.json',
      ],
      gitattributes: [
        '*.tf text eol=lf',
        '*.tfvars text eol=lf',
      ],
    },
  },
  {
    id: 'env',
    name: 'Environment Files',
    icon: '🔐',
    category: 'tool',
    description: 'Environment variables',
    files: {
      gitignore: [
        '# Environment files',
        '.env',
        '.env.local',
        '.env.development.local',
        '.env.test.local',
        '.env.production.local',
        '.env.*',
        '!.env.example',
        '!.env.template',
      ],
    },
  },
];

export const getTechnologyById = (id: string): TechnologyTemplate | undefined => {
  return technologies.find((t) => t.id === id);
};

export const searchTechnologies = (query: string): TechnologyTemplate[] => {
  const lowerQuery = query.toLowerCase();
  return technologies.filter(
    (t) =>
      t.name.toLowerCase().includes(lowerQuery) ||
      t.description.toLowerCase().includes(lowerQuery) ||
      t.category.toLowerCase().includes(lowerQuery)
  );
};
